name: CI Release

on:
    workflow_dispatch:

jobs:
    check-branch:
        runs-on: ubuntu-latest
        name: Branch format
        outputs:
            match: ${{ steps.check-branch.outputs.match }}
        steps:
            - name: Check Branch format
              run: |
               if [[ ${{ github.ref }} =~ ^refs/heads/release/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
               echo "match=true" >> $GITHUB_OUTPUT
               fi

    prepare:
        needs: check-branch
        runs-on: ubuntu-latest
        if: needs.check-branch.outputs.match == 'true'
        outputs:
            build-number: ${{ steps.prepare.outputs.build-number }}
        steps:
            - name: Prepare
              id: prepare
              run: |
                echo "build-number=B-123" >> $GITHUB_OUTPUT
                echo "ref: ${{ github.ref }}"

    main:
        needs: prepare
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Build Step
              run: echo "Build"