name: CI Release

on:
    workflow_dispatch:

jobs:
    prepare:
        runs-on: ubuntu-latest
        if: run echo "${{ github.ref }}" | grep -E 'release/v[0-9]+.[0-9]+.[0-9]+' && echo $? -eq 0
        outputs:
            build-number: ${{ steps.prepare.outputs.build-number }}
        steps:
            - name: Prepare
              id: prepare
              run: |
                echo "build-number=B-123" >> $GITHUB_OUTPUT

    main:
        needs: prepare
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Build Step
              run: echo "Build"