name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    
env:
    NODE_VERSION: 'xx.xx'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
        - uses: actions/checkout@v3
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'

        - name: Install Dependencies
          run: yarn install
    
        - name: Unit testing
          run: |
            yarn test
        - run: echo "run_number is ${{ github.run_number }}"
